# Generated by Django 4.1.3 on 2022-12-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='device.type'),
            preserve_default=False,
        ),
    ]
