# Generated by Django 4.1.3 on 2022-12-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.employee'),
        ),
    ]
