# Generated by Django 4.1.3 on 2022-12-02 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0006_history_timestamp_history_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Log',
        ),
    ]
